---
title: "EDA"
output: github_document
---

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(ggthemes))
```

```{r setup, include=FALSE}
smart_survey <- read_csv("data/smartphone_clean.csv")
```

```{r}
kable(head(smart_survey))
```

```{r}
sum_stats <- smart_survey %>%
  select(num_smartphone_OS,smartphone_OS_years,num_PC_OS,PC_OS_years) %>%
  summary()

kable(sum_stats)
```

```{r echo=FALSE}
smart_survey %>%
  ggplot(aes(x=smartphone_OS,fill=smartphone_OS)) +
  geom_bar() +
  xlab("") +
  ylab("") +
  ggtitle("Smartphone OS")+
  theme(legend.position = "none")
```

```{r}
smart_survey %>%
  filter(smartphone_OS=="iOS") %>%
  ggplot(aes(x=num_smartphone_OS)) +
  geom_bar() +
  ggtitle("Level of satisfaction of iOS users") +
  ylab("") +
  xlab("") +
  expand_limits(x=1) 
```

```{r}
smart_survey %>%
  filter(smartphone_OS=="Android") %>%
  ggplot(aes(x=num_smartphone_OS)) +
  geom_bar() +
  ggtitle("Level of satisfaction of Android users") +
  ylab("") +
  xlab("") +
  expand_limits(x=1)
```

```{r echo=FALSE}
smart_survey %>%
  ggplot(aes(x=future_smartphone_OS,fill=future_smartphone_OS)) +
  geom_bar() +
  xlab("") +
  ylab("") +
  ggtitle("Future Smartphone OS") +
  theme(legend.position = "none")
```

```{r echo=FALSE}
smart_survey %>%
  ggplot(aes(x=PC_OS)) +
  geom_bar() +
  xlab("") +
  ylab("") +
  ggtitle("Current Laptop OS")+
  theme(legend.position = "none")
```

```{r}
smart_survey %>%
  filter(PC_OS=="MacOS") %>%
  ggplot(aes(x=num_PC_OS)) +
  geom_bar() +
  ggtitle("Level of satisfaction of MacOS users") +
  ylab("") +
  xlab("") +
  expand_limits(x=1)
```

```{r}
smart_survey %>%
  filter(PC_OS=="Windows") %>%
  ggplot(aes(x=num_PC_OS)) +
  geom_bar() +
  ggtitle("Level of satisfaction of Windows users") +
  ylab("") +
  xlab("") +
  expand_limits(x=1)
```

```{r}
smart_survey %>%
  ggplot(aes(x=future_PC_OS)) +
  geom_bar() +
  xlab("") +
  ylab("") +
  ggtitle("Future PC Operating System")
```

```{r}
smart_survey %>%
  filter(PC_OS %in% c("Windows","MacOS")) %>%
  ggplot(aes(x=PC_OS,y=smartphone_OS)) +
  geom_bin2d() +
  ylab("Smartphone OS") +
  xlab("Laptop OS")
```
